WIP .githooks

diff --git a/.githooks/pre-merge-commit b/.githooks/pre-merge-commit
--- a/.githooks/pre-merge-commit
+++ b/.githooks/pre-merge-commit
@@ -1,45 +1,45 @@
-# !/bin/bash
+# # !/bin/bash
 
-# -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
-# TODO: Try again: pre-merge hooks are not well defined in git
+# # -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
+# # TODO: Try again: pre-merge hooks are not well defined in git
 
-# -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
-echo ".GITHOOKS/PRE_MERGE_COMMIT"
-echo
+# # -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
+# echo ".GITHOOKS/PRE_MERGE_COMMIT"
+# echo
 
-if [[ "${_GITHOOKS_IGNORE}" -eq 1 ]]; then
-    echo "IGNORING HOOKS"
-    exit 0 
-fi
+# if [[ "${_GITHOOKS_IGNORE}" -eq 1 ]]; then
+#     echo "IGNORING HOOKS"
+#     exit 0 
+# fi
 
-# -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
-# Keep all updated
-git fetch &
+# # -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
+# # Keep all updated
+# git fetch &
 
-# -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
-branch="$(git rev-parse --abbrev-ref HEAD)"
-# from this answer: https://stackoverflow.com/a/68187853/10480758
-behind_count=$(git rev-list --count HEAD..@{u})
-ahead_count=$(git rev-list --count @{u}..HEAD)
+# # -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
+# branch="$(git rev-parse --abbrev-ref HEAD)"
+# # from this answer: https://stackoverflow.com/a/68187853/10480758
+# behind_count=$(git rev-list --count HEAD..@{u})
+# ahead_count=$(git rev-list --count @{u}..HEAD)
 
-# -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
-# Check main is uptoday
-if [[ "$branch" == "main" ]]; then
-  echo "behind_count: ${behind_count}"
-  echo "ahead_count: ${ahead_count}"
-  if [[ "$behind_count" -eq 0 ]]; then
-      echo "GOOD: nothing new on 'origin/main'"
-  elif [[ "$behind_count" -ge 1 && "$ahead_count" -ge 1  ]]; then
-      echo "ERROR: Your branch and 'origin/main' have diverged"
-      echo "Set `export _GITHOOKS_IGNORE=1` to force"
-      echo
-      git status
-      exit 1
-  else
-      echo "ERROR: 'main' is behind 'origin/main'"
-      echo "Set `export _GITHOOKS_IGNORE=1` to force"
-      echo
-      git status
-      exit 1
-  fi
-fi
+# # -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
+# # Check main is uptoday
+# if [[ "$branch" == "main" ]]; then
+#   echo "behind_count: ${behind_count}"
+#   echo "ahead_count: ${ahead_count}"
+#   if [[ "$behind_count" -eq 0 ]]; then
+#       echo "GOOD: nothing new on 'origin/main'"
+#   elif [[ "$behind_count" -ge 1 && "$ahead_count" -ge 1  ]]; then
+#       echo "ERROR: Your branch and 'origin/main' have diverged"
+#       echo "Set `export _GITHOOKS_IGNORE=1` to force"
+#       echo
+#       git status
+#       exit 1
+#   else
+#       echo "ERROR: 'main' is behind 'origin/main'"
+#       echo "Set `export _GITHOOKS_IGNORE=1` to force"
+#       echo
+#       git status
+#       exit 1
+#   fi
+# fi
